// Example contact list data for development purposes as a JSON file to simulate a database

export const contactList = [
  {
    id: 1,
    name: "John Doe",
    email: "JDoe@gmail.com",
    phone: "123-456-7890",
    company: "Google",
    url: "https://picsum.photos/200",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "JaneDoe@gmail.com",
    phone: "123-456-7890",
    company: "Facebook",
    url: "https://picsum.photos/200",
  },
  {
    id: 3,
    name: "John Smith",
    email: "JSmith@gmail.com",
    phone: "123-456-7890",
    company: "Apple",
    url: "https://picsum.photos/200",
  },
  {
    id: 4,
    name: "Cassio Zen",
    email: "cassiozen@gmail.com",
    phone: "123-456-7890",
    company: "Microsoft",
    url: "https://picsum.photos/200",
  },
  {
    id: 5,
    name: "Dan Abramov",
    email: "gaearon@somewhere.com",
    phone: "123-456-7890",
    company: "Amazon",
    url: "https://picsum.photos/200",
  },
  {
    id: 6,
    name: "Pete Hunt",
    email: "floydophone@somewhere.com",
    phone: "123-456-7890",
    company: "Google",
    url: "https://picsum.photos/200",
  },
  {
    id: 7,
    name: "Paul O’Shannessy",
    email: "zpao@somewhere.com",
    phone: "123-456-7890",
    company: "Facebook",
    url: "https://picsum.photos/200",
  },
  {
    id: 8,
    name: "Ryan Florence",
    email: "rpflorence@somewhere.com",
    phone: "123-456-7890",
    company: "Apple",
    url: "https://picsum.photos/200",
  },
  {
    id: 9,
    name: "Sebastian Markbage",
    email: "sebmarkbage@here.com",
    phone: "123-456-7890",
    company: "Microsoft",
    url: "https://picsum.photos/200",
  },
  {
    id: 10,
    name: "John Doe",
    email: "JDoe@gmail.com",
    phone: "123-456-7890",
    company: "Google",
    url: "https://picsum.photos/200",
  },
  {
    id: 11,
    name: "Jane Doe",
    email: "JaneDoe@gmail.com",
    phone: "123-456-7890",
    company: "Facebook",
    url: "https://picsum.photos/200",
  },
  {
    id: 12,
    name: "John Smith",
    email: "JSmith@gmail.com",
    phone: "123-456-7890",
    company: "Apple",
    url: "https://picsum.photos/200",
  },
  {
    id: 13,
    name: "Cassio Zen",
    email: "cassiozen@gmail.com",
    phone: "123-456-7890",
    company: "Microsoft",
    url: "https://picsum.photos/200",
  },
  {
    id: 14,
    name: "Dan Abramov",
    email: "gaearon@somewhere.com",
    phone: "123-456-7890",
    company: "Amazon",
    url: "https://picsum.photos/200",
  },
  {
    id: 15,
    name: "Pete Hunt",
    email: "floydophone@somewhere.com",
    phone: "123-456-7890",
    company: "Google",
    url: "https://picsum.photos/200",
  },
  {
    id: 16,
    name: "Paul O’Shannessy",
    email: "zpao@somewhere.com",
    phone: "123-456-7890",
    company: "Facebook",
    url: "https://picsum.photos/200",
  },
  {
    id: 17,
    name: "Ryan Florence",
    email: "rpflorence@somewhere.com",
    phone: "123-456-7890",
    company: "Apple",
    url: "https://picsum.photos/200",
  },
  {
    id: 18,
    name: "Sebastian Markbage",
    email: "sebmarkbage@here.com",
    phone: "123-456-7890",
    company: "Microsoft",
    url: "https://picsum.photos/200",
  },
];
