import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";
import { colors, fonts } from "../../../config/global";
const { width, height } = Dimensions.get("window");

export const creditCardViewStyles = StyleSheet.create({
  background: {
    backgroundColor: colors.primary,
    // top: height * 0.15,
    // left: width * 0.03,
    height: height * 0.26,
    width: width * 0.94,
    // maxHeight: 200,
    // maxWidth: 400,
    borderRadius: 20,
    marginTop: 30,
    marginLeft: width * 0.03,
  },
  logoContainer: {
    // flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  logo: {
    height: 50,
    width: 50,
    borderRadius: 25,
    marginLeft: 20,
    // marginTop: 10,
  },
  headerText: {
    color: "white",
    fontSize: 15,
    fontWeight: "bold",
    textAlign: "center",
    // marginTop: 10,
    marginLeft: 10,
    // flex: 1,
    // backgroundColor: "red",
    flexWrap: "wrap",
    fontFamily: fonts.primary,
  },
  name: {
    textAlign: "center",
    marginLeft: 10,
    color: "white",
    marginTop: 10,
    flexWrap: "wrap",
    fontFamily: fonts.primary,
    fontWeight: "bold",
  },
  balanceContainer: {
    color: "white",
    flexDirection: "row",
    // textAlign: "center",
    // alignContent: "center",
    // justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
    position: "absolute",
    top: height * 0.12,
  },
  balanceText: {
    color: "white",
    marginRight: 10,
    fontFamily: fonts.primary,
    fontWeight: "bold",
  },
  amountContainer: {
    // color: "white",
    // textAlign: "center",
    // justifyContent: "center",
    position: "absolute",
    top: height * 0.15,
  },
  amountText: {
    // textAlign: "center",
    fontSize: 25,
    marginTop: 5,
    color: "black",
    marginLeft: 10,
  },
  date: {
    textAlign: "left",
    color: "white",
    marginLeft: 10,
    position: "absolute",
    bottom: 10,
    fontFamily: fonts.primary,
    fontWeight: "bold",
  },
  imageContainer: {
    // position: "absolute",
    alignItems: "center",
    // top: 10,
    // left: 10,
    marginTop: 10,
    marginLeft: 10,
  },
  image: {
    height: 80,
    width: 80,
    borderRadius: 40,
  },
  addImageIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "white",
    borderRadius: height * 0.1,
  },
});
